image: r.clrhs.dk/drone-builder
script:
  - psql -c 'create database app_test;' -U postgres
  - bundle exec rake ar:migrate --trace
  - bundle install --without development --path vendor/bundle
services:
  - postgres
